(function () {
  const config = window.FUCK_FACE_CONFIG;
  const client = config?.url && config?.anonKey && window.supabase ? window.supabase.createClient(config.url, config.anonKey) : null;
  const loginView=document.getElementById('loginView'), adminView=document.getElementById('adminView'), message=document.getElementById('message'), loginMessage=document.getElementById('loginMessage'), inventory=document.getElementById('inventoryList');
  function notice(text,type='success',target=message){if(!target)return;target.textContent=text;target.className=`message show ${type}`;setTimeout(()=>target.className='message',5000)}
  function filename(name){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-').toLowerCase()}
  async function isAdmin(){const {data:{user}}=await client.auth.getUser(); if(!user)return false; const {data}=await client.from('admin_profiles').select('user_id').eq('user_id',user.id).maybeSingle(); return Boolean(data)}
  async function setup(){if(!client){notice('Falta configurar Supabase en config.js.','error',loginMessage);return}try{if(await isAdmin()){loginView.hidden=true;adminView.hidden=false;await loadData()}else{loginView.hidden=false;adminView.hidden=true}}catch(error){console.error('No se pudo verificar la sesión de Supabase:',error);notice(error.message||'No se pudo conectar con Supabase.','error',loginMessage)}}
  document.getElementById('loginForm').addEventListener('submit',async event=>{event.preventDefault();if(!client){notice('Falta configurar Supabase en config.js.','error',loginMessage);return}const button=event.currentTarget.querySelector('button');button.disabled=true;button.textContent='INGRESANDO...';try{const {error}=await client.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(error){console.error('Error iniciando sesión en Supabase:',error);notice(error.message,'error',loginMessage);return}if(!(await isAdmin())){await client.auth.signOut();notice('Tu usuario no tiene permiso para este panel. Autorízalo en admin_profiles.','error',loginMessage);return}await setup()}catch(error){console.error('Error iniciando sesión en Supabase:',error);notice(error.message||'No se pudo iniciar sesión. Revisa la conexión y la configuración de Supabase.','error',loginMessage)}finally{button.disabled=false;button.textContent='INGRESAR ↗'}});
  document.getElementById('logoutButton').addEventListener('click',async()=>{await client.auth.signOut();await setup()});
  document.getElementById('images').addEventListener('change',event=>{const count=event.target.files.length;document.getElementById('fileCount').textContent=count?`${count} archivo${count!==1?'s':''} seleccionado${count!==1?'s':''}`:'Seleccionar archivos'});
  async function uploadImages(files){const {data:{user}}=await client.auth.getUser();const selected=[...files].slice(0,4);if(!selected.length)throw new Error('Seleccioná al menos una foto.'); if(files.length>4)throw new Error('Podés cargar un máximo de 4 fotos.');const urls=[];for(const file of selected){if(file.size>5*1024*1024)throw new Error('Cada imagen debe pesar menos de 5 MB.');const path=`${user.id}/${Date.now()}-${crypto.randomUUID()}-${filename(file.name)}`;const {error}=await client.storage.from('product-images').upload(path,file,{upsert:false});if(error)throw error;const {data}=client.storage.from('product-images').getPublicUrl(path);urls.push(data.publicUrl)}return urls}
  document.getElementById('productForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;button.textContent='SUBIENDO...';try{const data=new FormData(event.currentTarget);const image_urls=await uploadImages(document.getElementById('images').files);const {error}=await client.from('products').insert({name:data.get('name'),price:Number(data.get('price')),category:data.get('category'),size:data.get('size')||null,condition:data.get('condition')||null,description:data.get('description')||null,image_urls,status:'new_drop'});if(error)throw error;event.currentTarget.reset();document.getElementById('fileCount').textContent='Seleccionar archivos';notice('Pieza agregada a New Drop.');await loadData()}catch(error){console.error(error);notice(error.message||'No se pudo agregar la pieza.','error')}finally{button.disabled=false;button.textContent='AGREGAR A NEW DROP'}});
  document.getElementById('dropForm').addEventListener('submit',async event=>{event.preventDefault();const releaseAt=document.getElementById('releaseAt').value;if(new Date(releaseAt)<=new Date()){notice('Elegí una fecha futura.','error');return}const {error:offError}=await client.from('drops').update({is_active:false}).eq('is_active',true);if(offError){notice(offError.message,'error');return}const {error}=await client.from('drops').insert({release_at:new Date(releaseAt).toISOString(),description:document.getElementById('dropText').value||null,is_active:true});if(error){notice(error.message,'error');return}notice('Drop programado correctamente.');await loadData()});
  async function loadData(){await client.rpc('release_due_drops');const [{data:products,error},{data:drops}]=await Promise.all([client.from('products').select('*').order('created_at',{ascending:false}),client.from('drops').select('*').eq('is_active',true).order('release_at',{ascending:true}).limit(1)]);if(error){notice(error.message,'error');return}const drop=drops?.[0];document.getElementById('activeDrop').textContent=drop?`ACTIVO: ${new Date(drop.release_at).toLocaleString('es-CR',{dateStyle:'medium',timeStyle:'short'})}`:'SIN DROP PROGRAMADO';if(drop){document.getElementById('releaseAt').value=new Date(drop.release_at).toISOString().slice(0,16);document.getElementById('dropText').value=drop.description||''}document.getElementById('inventoryCount').textContent=`${products.length} PIEZAS`;inventory.innerHTML=products.map(product=>`<article class="inventory-row"><img src="${product.image_urls?.[0]||'img/logo1.jpg'}" alt=""><div><h3>${safe(product.name)}</h3><p>${safe(product.category)} · ${safe(product.size||'Sin talla')} · ₡${Number(product.price).toLocaleString('es-CR')}</p><span class="status ${product.status}">${product.status==='new_drop'?'NEW DROP':'PUBLICADA'}</span></div><button class="delete" data-delete="${product.id}">ELIMINAR</button></article>`).join('')||'<p>NO HAY PIEZAS TODAVÍA.</p>'}
  function safe(text=''){const node=document.createElement('span');node.textContent=text;return node.innerHTML}
  inventory.addEventListener('click',async event=>{const button=event.target.closest('[data-delete]');if(!button)return;if(!confirm('¿Eliminar esta pieza del inventario?'))return;const {error}=await client.from('products').delete().eq('id',button.dataset.delete);if(error){notice(error.message,'error');return}notice('Pieza eliminada.');await loadData()});
  setup();
})();
